#!/usr/bin/env bash
echo "Running detekt check..."

DETEKT_OUTPUT="/tmp/detekt-$(date +%s)"
./gradlew detektCheck >"$DETEKT_OUTPUT"
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  cat "$DETEKT_OUTPUT"
  rm "$DETEKT_OUTPUT"
  echo "***********************************************"
  echo "                 Detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi

echo "***********************************************"
echo "                 Detekt Success                "
echo "***********************************************"

rm "$DETEKT_OUTPUT"
